version: '3.8'

services:
  TodoApp:
    image: selmantopal/hepsiemlak:0.0.1
    environment:
      COUCHBASE_CONNECTION: couchbase:11210
      COUCHBASE_BUCKET: default
      COUCHBASE_USERNAME: Administrator
      COUCHBASE_PASSWORD: great123
      SWAGGER-UI-ENABLED: "true"
    ports:
      - 8080:8080

  couchbase:
    image: couchbase/server:community-7.1.0-aarch64
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    environment:
      CLUSTER_NAME: HepsiEmlak
      CLUSTER_USERNAME: Administrator
      CLUSTER_PASSWORD: great123
      BUCKET: default
    volumes:
      - couchbase-data:/opt/couchbase/var

volumes:
  couchbase-data: